### ISSUE TITLE
Cannot process argument transformation on parameter 'InstalledModuleInfo'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Management.Automation.PSModuleInfo"

### ISSUE THREAD

**Issue by bmanikm** [PowerShell/PowerShellGetv2#35]
Install Contoso module to multiple module paths in $env:PSModulePath then install another version using Install-Module instead of Update-Module.

``` powershell
PS C:\WINDOWS\system32> Install-Module Contoso -allowclobber
PackageManagement\Install-Package : Cannot process argument transformation on parameter 'InstalledModuleInfo'. Cannot
convert the "System.Object[]" value of type "System.Object[]" to type "System.Management.Automation.PSModuleInfo".
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1661 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Excep
   tion
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Validate-ModuleAuthenticodeSignature,Microsoft.Powe
   rShell.PackageManagement.Cmdlets.InstallPackage

```

**Comment by bmanikm** [comment]
Fixed in PR #44.

**Comment by pauldalyii** [comment]
I installed 1.1.2.0 still see this issue when attempting to `Install-Module AzureRM`.

```
PackageManagement\Install-Package : Cannot process argument transformation on parameter 'InstalledModuleInfo'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type 
"System.Management.Automation.PSModuleInfo".
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.1.2.0\PSModule.psm1:2089 char:20
+ ...           $sid = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Also, at first I had both 1.0.0.1 and 1.1.2.0 installed.  When I'd run `Install-Module AzureRM`, I'd see that 1.0.0.1 was being referenced in the error message.  I then forcefully uninstalled 1.0.0.1 using ([this](http://stackoverflow.com/questions/36097266/removing-a-powershell-module-using-its-version-number)):

```
function Remove-ModuleByVersion
{
    param (
        [Parameter(Mandatory=$true)]
        [string]
        $Module,

        [Parameter(Mandatory=$true)]
        [string]
        $VersionToMatch
    )

    Get-Module $Module | where {([string]($_.Version)).StartsWith($VersionToMatch)} | Remove-Module -Verbose
}

Remove-ModuleByVersion 'PowerShellGet' '1.0.0.1'
```
After doing removing v1.0.0.1, the error message still occurs, but it now references v1.1.2.0,

**Comment by pauldalyii** [comment]
After installing v1.1.2.0 of PowerShellGet, I still see this issue when I run `Install-Module AzureRM`:

```
PackageManagement\Install-Package : Cannot process argument transformation on parameter 'InstalledModuleInfo'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type 
"System.Management.Automation.PSModuleInfo".
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.1.2.0\PSModule.psm1:2089 char:20
+ ...           $sid = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

At first, the error message still referenced v1.0.0.1 of PowerShellGet.  I turns out that v1.0.0.1 and v1.1.2.0 were both installed.  I uninstalled v1.0.0.1 using [this](http://stackoverflow.com/questions/36097266/removing-a-powershell-module-using-its-version-number).  

```
function Remove-ModuleByVersion
{
    param (
        [Parameter(Mandatory=$true)]
        [string]
        $Module,

        [Parameter(Mandatory=$true)]
        [string]
        $VersionToMatch
    )

    Get-Module $Module | where {([string]($_.Version)).StartsWith($VersionToMatch)} | Remove-Module -Verbose
}

Remove-ModuleByVersion 'PowerShellGet' '1.0.0.1'
```

I still get the error message above, but now it references v1.1.2.0 PowerShellGet.

It seems like this issue is still present even after PR #44.

**Comment by bmanikm** [comment]
@pauldalyii, could you please provide consistent repro steps to repro this issue on a clean machine?

**Comment by brettcannon** [comment]
I ran into this today trying to do `Install-Module Azure -AllowClobber -Force` on Windows 10 Anniversary (it said Azure 2.1.0 was already installed, hence the Force). The fix a co-worker found which worked for me was to clear out the Azure-related stuff in:
* %ProgramFiles%\WindowsPowerShell\Modules folder
* %ProgramFiles(x86)%\Microsoft SDKs\Azure\PowerShell
